services:
  postgres-db:
    image: postgres:9.6
    mem_limit: '6g'
    memswap_limit: '6g'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - .:/pgdata:/var/lib/postgresql/data
